application: pongv4-3
module: default
version: 1
runtime: python27
api_version: 1
threadsafe: yes

inbound_services:
- channel_presence

handlers:
- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /img
  static_dir: img

- url: /favicon.ico
  static_files: img/atari.ico
  upload: img/atari.ico

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest